name: CI

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  pre:
    name: Preprocessing
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "matrix=$(python3 get_endpoints.py)" >> $GITHUB_OUTPUT
        id: matrix
      - name: Enumerate outputs
        run: |
          echo 'matrix:    ${{ steps.matrix.outputs.matrix }}'

  main:
    needs: [pre]
    timeout-minutes: 20
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.pre.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.11"
      - run: pip install pandas pyarrow
      - run: curl -fLO ${{ matrix.url }}
      - run: python3 build_one_quarter.py ${{ matrix.url }}
      - run: rm -f *.zip
      - run: zip ${{ matrix.file_stem }}.zip *.parquet

      - name: release files
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          files: ${{ matrix.file_stem }}.zip
