name: Summarize

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  pre:
    name: Preprocessing
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "matrix=$(python3 inspect/get_endpoints.py)" >> $GITHUB_OUTPUT
        id: matrix
      - name: Enumerate outputs
        run: |
          echo 'matrix:    ${{ steps.matrix.outputs.matrix }}'

  main:
    needs: [pre]
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.pre.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - run: pip install pandas pyarrow tqdm
      - run: aria2c --continue=true ${{ matrix.dl_url }}
      - run: python3 inspect/run.py ${{ matrix.name }}
      - uses: actions/upload-artifact@v4
        with:
          name: summary-${{ matrix.name }}
          path: summary-${{ matrix.name }}.json
  post:
    needs: [main]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: pip install tqdm
      - run: python3 inspect/join.py
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.3
          files: summary.json
